[{
	"tabName":"最热",
	"tabData":[
		{"imgSrc":"../assets/img/lamp01.png"},
		{"imgSrc":"../assets/img/lamp01.png"},
		{"imgSrc":"../assets/img/lamp01.png"},
		{"imgSrc":"../assets/img/lamp01.png"},
		{"imgSrc":"../assets/img/lamp01.png"},
		{"imgSrc":"../assets/img/lamp01.png"},
		{"imgSrc":"../assets/img/lamp01.png"},
		{"imgSrc":"../assets/img/lamp01.png"},
		{"imgSrc":"../assets/img/lamp01.png"},
		{"imgSrc":"../assets/img/lamp01.png"},
		{"imgSrc":"../assets/img/lamp01.png"}
	],
	"isActive":true
  },{
	"tabName":"类型",
	"tabData":[
		{"imgSrc":"../assets/img/lamp01.png"},
		{"imgSrc":"../assets/img/lamp01.png"},
		{"imgSrc":"../assets/img/lamp01.png"},
		{"imgSrc":"../assets/img/lamp01.png"},
		{"imgSrc":"../assets/img/lamp01.png"},
		{"imgSrc":"../assets/img/lamp01.png"},
		{"imgSrc":"../assets/img/lamp01.png"},
		{"imgSrc":"../assets/img/lamp01.png"},
		{"imgSrc":"../assets/img/lamp01.png"},
		{"imgSrc":"../assets/img/lamp01.png"},
		{"imgSrc":"../assets/img/lamp01.png"}
	],
	"isActive":false
  },{
	"tabName":"风格",
	"tabData":[
		{"imgSrc":"../assets/img/lamp01.png"},
		{"imgSrc":"../assets/img/lamp01.png"},
		{"imgSrc":"../assets/img/lamp01.png"},
		{"imgSrc":"../assets/img/lamp01.png"},
		{"imgSrc":"../assets/img/lamp01.png"},
		{"imgSrc":"../assets/img/lamp01.png"},
		{"imgSrc":"../assets/img/lamp01.png"},
		{"imgSrc":"../assets/img/lamp01.png"},
		{"imgSrc":"../assets/img/lamp01.png"},
		{"imgSrc":"../assets/img/lamp01.png"},
		{"imgSrc":"../assets/img/lamp01.png"}
	],
	"isActive":false
  }]